### ISSUE TITLE
"sanitize_smiles" not defined

### ISSUE THREAD

**Issue by zemanet2020** [CDDLeiden/QSPRpred#1]
"sanitize_smiles" is called in predict_CLI.py, but this function is not defined in data/utils/smiles_standardization.py or anywhere.

**Comment by martin-sicho** [comment]
Hi, very sorry for the late reply! Can you try in the new snapshot? You can install it like this:

```bash
pip install git+https://github.com/CDDLeiden/QSPRPred.git@v2.0.0.dev1
```

The problem should be fixed there.

**Comment by martin-sicho** [comment]
Closed for inactivity. Let us know if you still need help.
